### ISSUE TITLE
Don't use hard-coded tmp paths

### ISSUE THREAD

**Issue by rickynils** [danidiaz/tailfile-hinotify#2]
In https://github.com/danidiaz/tailfile-hinotify/blob/master/tests/tests.hs#L123, hard-coded paths to files in `/tmp` are used. This cause troubles for some build systems and non-standard tmp setups.

It would be better to use some portable library to provide temporary directories, or use the `$TMPDIR` environment variable.

**Comment by danidiaz** [comment]
Thanks for the notice. In version 1.0.0.3 I use `System.Directory.getTemporaryDirectory` , which returns `$TMPDIR` if it is defined, or else `/tmp` as fallback.
